from .AuthGroup_admin import AuthGroupAdmin
from .AuthPermission_admin import AuthPermissionAdmin
from .AuthPermission_admin import AuthPermissionAdmin
from .AuthUser_admin import AuthUserAdmin
from .AuthUserGroup_admin import AuthUserGroupAdmin
from .AuthUserUserPermission_admin import AuthUserUserPermissionAdmin

from .DjangoContentType_admin import DjangoContentTypeAdmin

from .CompanyCategory_admin import CompanyCategoryAdmin
from .CompanyItem_admin import CompanyItemAdmin
from .Organization_admin import OrganizationAdmin

from .Tenant_admin import TenantAdmin