# Generated by Django 5.2.10 on 2026-01-27 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=32, unique=True)),
                ('project_title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_active', default='Y', max_length=1, verbose_name='Is Active Check')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Project',
                'db_table': 'project',
                'ordering': ['project_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectStructure',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('project_structure_id', models.BigAutoField(db_column='project_structure_id', primary_key=True, serialize=False, verbose_name='Project Structure ID')),
                ('structure_code', models.CharField(db_column='structure_code', max_length=50, verbose_name='Structure Code')),
                ('structure_title', models.CharField(db_column='structure_title', max_length=255, verbose_name='Structure Title')),
                ('structure_level', models.PositiveSmallIntegerField(db_column='structure_level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Structure Level (1–6)')),
                ('structure_role', models.CharField(choices=[('SPATIAL', 'Spatial – grouping by physical location or layout'), ('SYSTEMIC', 'Systemic – grouping by system relationships'), ('PROCESS', 'Process – grouping by execution or workflow logic'), ('PRESENTATION', 'Presentation – grouping for views, dashboards, or rollups'), ('TRANSIENT', 'Transient – grouping intended to be temporary or non-persistent')], db_column='structure_role', default='SPATIAL', help_text='Defines the lens used to organise the project structure. This describes how information is grouped for understanding or navigation, not physical assets, disciplines, or project phases.', max_length=20, verbose_name='Structure Role')),
                ('comments', models.CharField(blank=True, db_column='comments', max_length=2000, null=True, verbose_name='Comments')),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_active', default='Y', max_length=1, verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(db_column='sort_order', default=0, verbose_name='Sort Order')),
                ('parent_project_structure', models.ForeignKey(blank=True, db_column='parent_project_structure_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.projectstructure', verbose_name='Parent Structure Node')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='project.project', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'Project Structures',
                'db_table': 'project_structure',
                'ordering': ['project_id', 'structure_level', 'sort_order', 'structure_code'],
                'managed': True,
                'indexes': [models.Index(fields=['project'], name='idx_ps_project'), models.Index(fields=['parent_project_structure'], name='idx_ps_parent'), models.Index(fields=['project', 'structure_level'], name='idx_ps_project_level'), models.Index(fields=['project', 'structure_role'], name='idx_ps_project_role')],
                'unique_together': {('project', 'parent_project_structure', 'structure_code')},
            },
        ),
    ]
