# Generated by Django 5.2.10 on 2026-01-27 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('inspection_template_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inspection Template ID')),
                ('inspection_template_code', models.CharField(max_length=50, unique=True, verbose_name='Inspection Template Code')),
                ('inspection_template_title', models.CharField(max_length=255, verbose_name='Inspection Template Title')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'B | 01 | Inspection Templates',
                'db_table': 'inspection_template',
                'ordering': ['inspection_template_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateItem',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('inspection_template_item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inspection Template Item ID')),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_prompt', models.CharField(max_length=500, verbose_name='Item Prompt')),
                ('item_type', models.CharField(max_length=20, verbose_name='Item Type')),
            ],
            options={
                'verbose_name_plural': 'C / Inspection Template Items',
                'db_table': 'inspection_template_item',
                'ordering': ['item_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('inspection_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inspection ID')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Inspected By')),
            ],
            options={
                'verbose_name_plural': 'C | Inspections',
                'db_table': 'inspection',
                'ordering': ['inspection_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionItemResult',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('inspection_item_result_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inspection Item Result ID')),
                ('result_code', models.CharField(max_length=10, verbose_name='Result Code')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Measured Value')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('inspection_id', models.ForeignKey(db_column='inspection_id', on_delete=django.db.models.deletion.RESTRICT, related_name='i_j_iir', to='or.inspection', verbose_name='Inspection')),
                ('inspection_template_item_id', models.ForeignKey(db_column='inspection_template_item_id', on_delete=django.db.models.deletion.RESTRICT, related_name='iti_j_iir', to='or.inspectiontemplateitem', verbose_name='Inspection Template Item')),
            ],
            options={
                'verbose_name_plural': 'D | 01 | Inspection Item Results',
                'db_table': 'inspection_item_result',
                'ordering': ['inspection_item_result_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('inspection_evidence_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inspection Evidence ID')),
                ('evidence_type_code', models.CharField(max_length=20, verbose_name='Evidence Type Code')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='inspection_evidence/', verbose_name='File')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('inspection_item_result_id', models.ForeignKey(db_column='inspection_item_result_id', on_delete=django.db.models.deletion.RESTRICT, related_name='iir_j_ie', to='or.inspectionitemresult', verbose_name='Inspection Item Result')),
            ],
            options={
                'verbose_name_plural': 'D | 02 | Inspection Evidence',
                'db_table': 'inspection_evidence',
                'ordering': ['inspection_evidence_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateVersion',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('inspection_template_version_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Inspection Template Version ID')),
                ('version_code', models.CharField(max_length=20, verbose_name='Version Code')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('inspection_template_id', models.ForeignKey(db_column='inspection_template_id', on_delete=django.db.models.deletion.RESTRICT, related_name='it_j_itv', to='or.inspectiontemplate', verbose_name='Inspection Template')),
            ],
            options={
                'verbose_name_plural': 'B | 02 | Inspection Template Versions',
                'db_table': 'inspection_template_version',
                'ordering': ['inspection_template_id', 'version_code'],
                'managed': True,
                'unique_together': {('inspection_template_id', 'version_code')},
            },
        ),
        migrations.AddField(
            model_name='inspectiontemplateitem',
            name='inspection_template_version_id',
            field=models.ForeignKey(db_column='inspection_template_version_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itv_j_iti', to='or.inspectiontemplateversion', verbose_name='Inspection Template Version'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_template_version_id',
            field=models.ForeignKey(db_column='inspection_template_version_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itv_j_i', to='or.inspectiontemplateversion', verbose_name='Inspection Template Version'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('project_asset_id', models.BigAutoField(db_column='project_asset_id', primary_key=True, serialize=False, verbose_name='Project Asset ID')),
                ('project_id', models.CharField(db_column='project_id', max_length=5, verbose_name='Project ID')),
                ('asset_code', models.CharField(db_column='asset_code', max_length=64, verbose_name='Asset Code')),
                ('asset_title', models.CharField(db_column='asset_title', max_length=255, verbose_name='Asset Title')),
                ('asset_role_code', models.CharField(db_column='asset_role_code', help_text='E.g. COMM, INSPECT, OPERATE', max_length=32, verbose_name='Asset Role Code')),
                ('asset_origin', models.CharField(choices=[('QUANTUM', 'From Quantum'), ('DIRECT', 'Direct / Discovery')], db_column='asset_origin', default='QUANTUM', max_length=16, verbose_name='Asset Origin')),
                ('asset_status', models.CharField(choices=[('PLANNED', 'Planned'), ('INSTALLED', 'Installed'), ('UNDER_TEST', 'Under Test'), ('COMPLETED', 'Completed'), ('ACCEPTED', 'Accepted')], db_column='asset_status', default='PLANNED', max_length=16, verbose_name='Asset Status')),
                ('comments', models.CharField(blank=True, db_column='comments', max_length=2000, null=True, verbose_name='Comments')),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_active', default='Y', max_length=1, verbose_name='Is Active Check')),
            ],
            options={
                'verbose_name_plural': 'A | Project Assets',
                'db_table': 'project_asset',
                'ordering': ['project_id', 'asset_code'],
                'managed': True,
                'unique_together': {('project_id', 'asset_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inspectiontemplateitem',
            unique_together={('inspection_template_version_id', 'item_code')},
        ),
        migrations.CreateModel(
            name='PunchItem',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('punch_item_id', models.BigAutoField(db_column='punch_item_id', primary_key=True, serialize=False, verbose_name='Punch Item ID')),
                ('project_id', models.CharField(db_column='project_id', max_length=5, verbose_name='Project ID')),
                ('punch_category', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D')], db_column='punch_category', max_length=1, verbose_name='Punch Category')),
                ('punch_code', models.CharField(db_column='punch_code', max_length=64, verbose_name='Punch Code')),
                ('punch_title', models.CharField(db_column='punch_title', max_length=255, verbose_name='Punch Title')),
                ('punch_description', models.CharField(db_column='punch_description', max_length=2000, verbose_name='Punch Description')),
                ('punch_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_CLOSE', 'Ready for Close'), ('CLOSED', 'Closed'), ('ACCEPTED', 'Accepted')], db_column='punch_status', default='OPEN', max_length=16, verbose_name='Punch Status')),
                ('raised_date', models.DateField(db_column='raised_date', verbose_name='Raised Date')),
                ('target_close_date', models.DateField(blank=True, db_column='target_close_date', null=True, verbose_name='Target Close Date')),
                ('closed_date', models.DateField(blank=True, db_column='closed_date', null=True, verbose_name='Closed Date')),
                ('comments', models.CharField(blank=True, db_column='comments', max_length=2000, null=True, verbose_name='Comments')),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_active', default='Y', max_length=1, verbose_name='Is Active Check')),
                ('inspection_id', models.ForeignKey(blank=True, db_column='inspection_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i_j_punch_item', to='or.inspection', verbose_name='Originating Inspection')),
                ('project_asset_id', models.ForeignKey(db_column='project_asset_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='pa_j_punch_item', to='or.projectasset', verbose_name='Project Asset')),
                ('raised_by', models.ForeignKey(blank=True, db_column='raised_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='au_j_pi', to='core.authuser', verbose_name='Raised By')),
            ],
            options={
                'verbose_name_plural': 'E | Punch Items',
                'db_table': 'punch_item',
                'ordering': ['project_id', 'punch_category', 'punch_code'],
                'managed': True,
                'unique_together': {('project_id', 'punch_code')},
            },
        ),
    ]
