# Generated by Django 5.2.10 on 2026-01-27 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('auth_group_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Group ID')),
                ('auth_group_name', models.CharField(db_column='name', max_length=150, unique=True, verbose_name='Group Name')),
            ],
            options={
                'verbose_name_plural': 'User Management / B / Authorised Group',
                'db_table': 'auth_group',
                'ordering': ['auth_group_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('auth_permission_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Authorised Permission ID')),
                ('auth_permission_name', models.CharField(db_column='name', max_length=255, verbose_name='Authorised Permission Name')),
                ('codename', models.CharField(db_column='codename', max_length=100, verbose_name='Codename')),
            ],
            options={
                'verbose_name_plural': 'User Management / C / Authorised Permissions',
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='User ID')),
                ('password', models.CharField(db_column='password', max_length=128, verbose_name='Password')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True, verbose_name='Last Login')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', verbose_name='Superuser Status')),
                ('username', models.CharField(db_column='username', max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(db_column='first_name', max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='last_name', max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(db_column='email', max_length=254, verbose_name='Email')),
                ('is_staff', models.BooleanField(db_column='is_staff', verbose_name='Staff Status')),
                ('is_active', models.BooleanField(db_column='is_active', verbose_name='Active')),
                ('date_joined', models.DateTimeField(db_column='date_joined', verbose_name='Date Joined')),
            ],
            options={
                'verbose_name_plural': 'User Management / A / Authorised User',
                'db_table': 'auth_user',
                'ordering': ['username'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroup',
            fields=[
                ('auth_user_group_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Auth User Group ID')),
            ],
            options={
                'verbose_name_plural': 'User Management / D / Authorised User Group',
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermission',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('auth_user_user_permission_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Authorised User User Permission')),
            ],
            options={
                'verbose_name_plural': 'User Management / F / Authorised User User Permissions',
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('django_content_type_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Django Content Type ID')),
                ('app_label', models.CharField(db_column='app_label', max_length=100, verbose_name='App Label')),
                ('model', models.CharField(db_column='model', max_length=100, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Django Content Type',
                'db_table': 'django_content_type',
                'ordering': ['app_label', 'model'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('company_category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Company Category ID')),
                ('company_category_code', models.CharField(help_text='10-letter category code', max_length=10, unique=True, verbose_name='Company Category Code')),
                ('company_category_title', models.CharField(max_length=255, unique=True, verbose_name='Company Category Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Organization / Company Category',
                'db_table': 'company_category',
                'ordering': ['company_category_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyItem',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('company_item_id', models.AutoField(db_column='company_item_id', primary_key=True, serialize=False, verbose_name='Company Item ID')),
                ('company_item_code', models.CharField(help_text='10-letter company code', max_length=10, verbose_name='Company Item Code')),
                ('company_item_title', models.CharField(max_length=255, verbose_name='Company Item Title')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company E-mail')),
                ('business_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Business Phone')),
                ('fax_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Fax Number')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 2')),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZIP/Postal Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('web_page', models.URLField(blank=True, max_length=250, null=True, verbose_name='Web Page')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('company_category_id', models.ForeignKey(db_column='company_category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='cc_j_ci', to='core.companycategory', verbose_name='Company Category ID')),
            ],
            options={
                'verbose_name_plural': 'Organization / Company Item',
                'db_table': 'company_item',
                'ordering': ['company_item_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('tenant_id', models.BigAutoField(db_column='tenant_id', primary_key=True, serialize=False, verbose_name='Tenant ID')),
                ('tenant_code', models.CharField(db_column='tenant_code', help_text='Unique system identifier for the tenant', max_length=20, unique=True, verbose_name='Tenant Code')),
                ('tenant_name', models.CharField(db_column='tenant_name', max_length=255, verbose_name='Tenant Name')),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_active', default='Y', max_length=1, verbose_name='Is Active')),
                ('comments', models.CharField(blank=True, db_column='comments', max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
                'ordering': ['tenant_code'],
                'managed': True,
                'indexes': [models.Index(fields=['tenant_code'], name='idx_tenant_code')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_deleted', db_default='N', default='N', max_length=1, verbose_name='Soft Delete Check')),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('organization_id', models.BigAutoField(db_column='organization_id', primary_key=True, serialize=False, verbose_name='Organization ID')),
                ('organization_code', models.CharField(db_column='organization_code', help_text='Tenant-scoped organization identifier', max_length=20, verbose_name='Organization Code')),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='is_active', default='Y', max_length=1, verbose_name='Is Active')),
                ('comments', models.CharField(blank=True, db_column='comments', max_length=2000, null=True, verbose_name='Comments')),
                ('company_item_id', models.ForeignKey(db_column='company_item_id', on_delete=django.db.models.deletion.RESTRICT, related_name='ci_j_org', to='core.companyitem', verbose_name='Company')),
                ('tenant_id', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_j_org', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
                'ordering': ['tenant_id', 'organization_code'],
                'managed': True,
                'indexes': [models.Index(fields=['tenant_id'], name='idx_org_tenant'), models.Index(fields=['company_item_id'], name='idx_org_company')],
                'unique_together': {('tenant_id', 'company_item_id'), ('tenant_id', 'organization_code')},
            },
        ),
    ]
